#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(PIN_MISSILE) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(GIGA_IMPACT) \
    F(REFLECT) \
    F(THUNDER_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(ROCK_SLIDE) \
    F(REST) \
    F(WILL_O_WISP) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SHADOW_CLAW) \
    F(OVERHEAT) \
    F(AQUA_JET) \
    F(ICICLE_SPEAR) \
    F(POISON_JAB) \
    F(DRAINING_KISS) \
    F(AIR_SLASH) \
    F(SMART_STRIKE) \
    F(LEECH_LIFE) \
    F(BUG_BUZZ) \
    F(WILD_CHARGE) \
    F(DRACO_METEOR) \
    F(PLAY_ROUGH) \
    F(DAZZLING_GLEAM) \
    F(DARK_PULSE) \
    F(THROAT_CHOP) \
    F(PSYCHO_CUT) \
    F(CLOSE_COMBAT) \
    F(DISABLE) \
    F(ENTRAINMENT) \
    F(MOONLIGHT) \
    F(HYPNOSIS) \
    F(NASTY_PLOT) \
    F(RECYCLE) \
    F(ROOST) \
    F(SHELL_SMASH) \
    F(SPIKES) \
    F(CONFUSE_RAY) \
    F(SMACK_DOWN) \
    F(BULLDOZE) \
    F(DRAGON_BREATH) \
    F(BUG_BITE) \
    F(CHARM) \
    F(VACUUM_WAVE) \
    F(DRAIN_PUNCH) \
    F(FLAME_CHARGE) \
    F(ACROBATICS) \
    F(OMINOUS_WIND) \
    F(SHADOW_SNEAK) \
    F(GRASS_KNOT) \
    F(SEED_BOMB) \
    F(EARTH_POWER) \
    F(HAZE) \
    F(AVALANCHE) \
    F(HYPER_VOICE) \
    F(VENOSHOCK) \
    F(POWER_GEM) \
    F(FLASH_CANNON) \
    F(IRON_HEAD) \
    F(SCALD) \
    F(ELECTROWEB)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
