GladehavenTown_House_MapScripts::
	.byte 0


GladehavenTown_House_EventScript_Woman::
# 6 "data/maps/GladehavenTown_House/scripts.pory"
	msgbox GladehavenTown_House_Text_Woman, MSGBOX_NPC
	return


GladehavenTown_House_EventScript_Girl::
# 14 "data/maps/GladehavenTown_House/scripts.pory"
	msgbox GladehavenTown_House_Text_Girl, MSGBOX_NPC
	return


GladehavenTown_House_Text_Woman::
# 9 "data/maps/GladehavenTown_House/scripts.pory"
	.string "Hi! My dad just outside our house loves\n"
	.string "to teach Fury cutter to random\l"
	.string "trainers passing by.\p"
	.string "If you haven't checked him out yet, you\n"
	.string "should.\p"
	.string "But he will only teach it to you once\n"
	.string "and he never forgets a face!$"

GladehavenTown_House_Text_Girl::
# 17 "data/maps/GladehavenTown_House/scripts.pory"
	.string "I'm so excited! Mom said we can go to\n"
	.string "the beach in Bay Harbor City later!$"
