GladehavenTown_House_MapScripts::
	.byte 0


GladehavenTown_House_EventScript_Woman::
# 6 "data/maps/GladehavenTown_House/scripts.pory"
	msgbox GladehavenTown_House_Text_Woman, MSGBOX_NPC
	return


GladehavenTown_House_EventScript_Girl::
# 14 "data/maps/GladehavenTown_House/scripts.pory"
	msgbox GladehavenTown_House_Text_Girl, MSGBOX_NPC
	return


GladehavenTown_House_Text_Woman::
# 9 "data/maps/GladehavenTown_House/scripts.pory"
	.string "Not_done$"

GladehavenTown_House_Text_Girl::
# 17 "data/maps/GladehavenTown_House/scripts.pory"
	.string "Not_done$"
