# 1 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 2 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_MapScripts::
# 3 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 5 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_EventScript_DevonEmployee::
# 6 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones, MSGBOX_NPC
# 7 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	end
# 8 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 9 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones, MSGBOX_NPC
# 11 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	end
# 12 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 13 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones:
# 14 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "Devon's President likes to collect\n"
# 15 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "rare stones.\p"
# 16 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I wonder if he has any evolution.\n"
# 17 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "stones in his collection.$"
# 18 "data/maps/RustboroCity_Flat2_3F/scripts.pory"

# 19 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones:
# 20 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I think the President's son can\n"
# 21 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "can revive Pokémon from their\p."
# 22 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "fossils.$"
